<amp-carousel width="720" height="720" layout="container" type="slides">
  <amp-img on="tap:lightbox1" role="button" tabindex="0" src="/common/img/carousel1.jpg" width="720" height="720" layout="responsive" alt="a sample image"></amp-img>
  <amp-img on="tap:lightbox1" role="button" tabindex="0" src="/common/img/carousel2.jpg" width="720" height="720" layout="responsive" alt="a sample image"></amp-img>
  <amp-img on="tap:lightbox1" role="button" tabindex="0" src="/common/img/carousel3.jpg" width="720" height="720" layout="responsive" alt="a sample image"></amp-img>
  <amp-img on="tap:lightbox1" role="button" tabindex="0" src="/common/img/carousel4.jpg" width="720" height="720" layout="responsive" alt="a sample image"></amp-img>
</amp-carousel>
<amp-image-lightbox id="lightbox1" layout="nodisplay">
    <button type="button" class="play-icon" on="tap:lightbox1.hide" title="close the lightbox1">close</button> 
</amp-image-lightbox>
<!-- <amp-carousel width="700" height="700" layout="responsive" type="slides">
      <div>
        <amp-img src="/common/img/carousel1.jpg" width="720" height="720" layout="responsive" alt="a sample image"></amp-img>
      </div>
      <div>
        <amp-img src="/common/img/carousel2.jpg" width="720" height="720" layout="responsive" alt="a sample image"></amp-img>
      </div>
      <div>
        <amp-img src="/common/img/carousel3.jpg" width="720" height="720" layout="responsive" alt="a sample image"></amp-img>
      </div>
</amp-carousel> -->