<article class="carousel-wrap" id="carouselWrap">
    <amp-carousel class="item" height="360" layout="fixed-height" type="carousel">
        <amp-img src="img/carousel1.jpg" alt="" width="360" height="360"></amp-img>
        <amp-img src="img/carousel2.jpg" alt="" width="360" height="360"></amp-img>
        <amp-img src="img/carousel3.jpg" alt="" width="360" height="360"></amp-img>
        <amp-img src="img/carousel4.jpg" alt="" width="360" height="360"></amp-img>
    </amp-carousel>
</article>