    <article>
        <header>
            <h2>신사동 예쁜 쓰리룸</h2>
        </header>
        <dl class="dl-table price">
            <dt>보증금</dt>
            <dd><em>10000</em>만원</dd>
            <dt>월세</dt>
            <dd><em>100</em>만원</dd>
            <dt>등록번호</dt>
            <dd>1234567</dd>
            <dd class="float">
                <button type="button" title="실거래가 확인">실거래가 확인<span class="logo">한국감정원</span></button>
            </dd>
        </dl>
        <dl class="dl-table">
            <dt>주소</dt>
            <dd>서울시 강남구 신사동</dd>
            <dt>인근전철역</dt>
            <dd>신사역(3호선) 압구정역(7호선)</dd>
            <dt>층/건물층수</dt>
            <dd>3층/4층</dd>
            <dt>크기</dt>
            <dd>전용면적 60.10㎡ 18.18P</dd>
            <dt>구조</dt>
            <dd>쓰리룸+</dd>
            <dt>건물형태</dt>
            <dd>다세대/다가구</dd>
        </dl>
        <dl class="dl-table">
            <dt>옵션</dt>
            <dd>옷장</dd>
            <dt>관리비</dt>
            <dd>없음</dd>
            <dt>관리비 포함항목</dt>
            <dd>수도</dd>
            <dt>주차</dt>
            <dd>불가능</dd>
            <dt>엘레베이터</dt>
            <dd>없음</dd>
            <dt>입주가능일</dt>
            <dd>4월21일 이후</dd>
        </dl>
    </article>
    <article>
        <header>
            <h2>상세설명</h2>
        </header>
        <div class="box box-white">
            <p>거실과 방이 크게 나온 신사동 3룸 입니다 ^^
            <br>남향집이고 해가 너무 잘들고 근처 건물둘에 비해서 집이 깨끗하고 뷰도 좋은 편입니다.
            <br>가격은 집주인 분과 상의 후에 조정 가능합니다!!
            <br>깔끔하고 좋은 집 보러 연락주세요!!
            </p>
        </div>
    </article>
    <article>
        <header>
            <h2>담당자 한마디</h2>
        </header>
        <div class="box box-white">
            <p>공휴일 및 주말에도 언제든지 상담 가능
            <br>차량 픽업 서비스 가능
            <br>조건에 맞는 집 답사
            <br>상담부터 계약까지 고객 맞춤형 서비스
            </p>
        </div>
    </article>
    <article>
        <header>
            <h2>건물정보</h2>
        </header>
        <div class="box box-white">
            
        </div>
    </article>
    <article>
        <header>
            <h2>위치보기</h2>
        </header>
        <div class="mapWrap">
        <!--#include virtual="/inc/map.inc" -->
        </div>
    </article>
    <article>
        <header>
            <h2>중개사정보</h2>
        </header>
        <section>
            <div class="box box-white">
                <div class="top">
                    <figure>
                        <amp-img src="/img/pic.jpg" width="200" height="150" alt="profile"></amp-img>
                        <figcaption><span class="label-safe">안심중개사<i>™</i></span></figcaption>
                    </figure>
                </div>
                <div class="bottom">
                    <h3>중개사무소 정보</h3>
                    <ul>
                        <li>서울시 마포구, 테리 부동산 (김테리)</li>
                        <li>대표번호 : 1588-1688</li>
                    </ul>
                </div>
            </div>
        </section>
    </article>