<head>
    <meta charset="utf-8">
    <title>Hello, This is Sangmi's Work</title>
    <link rel="amphtml" href="index.amp.html">
    <meta name="description" content="">
    <meta name="keyword" content="">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/common/css/style.css">
    <script type="text/javascript" src="/common/js/app.js"></script>
</head>